"""P1.5 — Schema dialect translation.

The SCHEMA string in `storage.py` is sqlite3-flavored. Two specific
incompatibilities matter for Postgres:

  1. `INTEGER PRIMARY KEY AUTOINCREMENT` is SQLite-only. Postgres
     uses `BIGSERIAL PRIMARY KEY` (or `GENERATED BY DEFAULT AS
     IDENTITY`).

  2. `TEXT NOT NULL DEFAULT (datetime('now'))` — the `datetime('now')`
     server-side default is SQLite-specific. Postgres uses
     `TIMESTAMPTZ DEFAULT now()` natively. We translate the
     server-side default expression; the column TYPE stays TEXT so
     downstream code that reads ISO-formatted strings keeps working
     unchanged.

Anything else in our schema is broadly portable (TEXT, INTEGER,
NOT NULL, DEFAULT '<string literal>', UNIQUE, foreign keys).

The translation is a string pass — we don't try to parse SQL.
Targeted regexes cover the two patterns above and nothing else.
Future schema slices that add Postgres-specific types (`JSONB`,
arrays) can extend this module.
"""

from __future__ import annotations

import re


# `INTEGER PRIMARY KEY AUTOINCREMENT` (case-insensitive, with optional
# whitespace) — SQLite's autoincrement PK. PG uses BIGSERIAL.
_AUTOINCREMENT_RE = re.compile(
    r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
    re.IGNORECASE,
)

# `DEFAULT (datetime('now'))` — SQLite server-side default. PG: now().
_DT_DEFAULT_RE = re.compile(
    r"DEFAULT\s+\(\s*datetime\(\s*'now'\s*\)\s*\)",
    re.IGNORECASE,
)

# `DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))` — SQLite ISO-8601
# millisecond timestamp default. We translate the exact format string
# we actually use; if a future schema adds a different strftime format,
# extend this regex (or switch to a real parser).
_STRFTIME_ISO_MS_DEFAULT_RE = re.compile(
    r"DEFAULT\s+\(\s*strftime\(\s*'%Y-%m-%dT%H:%M:%fZ'\s*,\s*'now'\s*\)\s*\)",
    re.IGNORECASE,
)


def translate_schema(sql: str, *, dialect: str) -> str:
    """Rewrite the SQLite schema string for the target dialect.

    `dialect` is `"sqlite"` (no-op) or `"postgres"`.
    """
    if dialect == "sqlite":
        return sql
    if dialect != "postgres":
        raise ValueError(f"unknown dialect: {dialect!r}")

    out = sql
    out = _AUTOINCREMENT_RE.sub("BIGSERIAL PRIMARY KEY", out)
    # `DEFAULT (datetime('now'))` → ISO-8601 microsecond UTC string.
    # PG won't implicitly cast `timestamptz` → `text` for a
    # `TEXT DEFAULT` column, so the explicit ISO format matters.
    out = _DT_DEFAULT_RE.sub(
        "DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.US'))",
        out,
    )
    # `DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))` → ISO-8601
    # millisecond UTC string ending in `Z`. SQLite's `%f` is
    # `SS.SSS` (seconds + fractional), which maps to PG `SS.MS`.
    out = _STRFTIME_ISO_MS_DEFAULT_RE.sub(
        "DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))",
        out,
    )
    return out


__all__ = ["translate_schema"]
