"""`retrace quickstart` — zero-config install path.

One command turns an empty directory into a working Retrace setup:

  * writes a minimal `config.yaml`
  * initializes the local SQLite store
  * ensures an org / project / environment
  * mints a browser-safe SDK key
  * prints a ready-to-paste `<script>` tag for the user's app

The promise: from `pip install retrace` to "the browser is sending replays"
in under two minutes, with no config questions.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

import click

from retrace.config import load_config
from retrace.sdk_keys import create_sdk_key
from retrace.storage import Storage


_DEFAULT_CONFIG_TEMPLATE = """# Generated by `retrace quickstart`. Edit freely.
posthog:
  host: https://us.i.posthog.com
  project_id: ""

llm:
  provider: openai_compatible
  base_url: http://localhost:8080/v1
  model: gpt-4o-mini

run:
  lookback_hours: 6
  max_sessions_per_run: 50
  output_dir: ./reports
  data_dir: ./data

detectors:
  console_error: true
  network_5xx: true
  network_4xx: true
  rage_click: true
  dead_click: true
  error_toast: true
  blank_render: true
  session_abandon_on_error: true

cluster:
  min_size: 1
"""


def _write_stub_files_if_missing(config_path: Path, env_path: Path) -> tuple[bool, bool]:
    """Create config.yaml + .env only if they don't already exist."""
    wrote_config = False
    wrote_env = False
    if not config_path.exists():
        config_path.write_text(_DEFAULT_CONFIG_TEMPLATE)
        wrote_config = True
    if not env_path.exists():
        env_path.write_text("RETRACE_POSTHOG_API_KEY=\nRETRACE_LLM_API_KEY=\n")
        wrote_env = True
    return wrote_config, wrote_env


def _emit_script_tag(*, api_key: str, ingest_url: str) -> str:
    """Render a copy-pasteable HTML snippet for the user's app `<head>`.

    Uses esm.sh so the user doesn't need an npm install in their app.
    Falls back to a clear local-dev variant when not yet published.
    """
    return (
        "<!-- Retrace replay + error capture -->\n"
        '<script type="module">\n'
        '  import { init } from "https://esm.sh/@retrace/browser@latest";\n'
        f"  init({{\n"
        f'    apiKey: "{api_key}",\n'
        f'    ingestUrl: "{ingest_url}",\n'
        "  });\n"
        "</script>\n"
        "<!-- Or, if you prefer npm:\n"
        '     npm i @retrace/browser   then:\n'
        '     import { init } from "@retrace/browser";\n'
        f'     init({{ apiKey: "{api_key}", ingestUrl: "{ingest_url}" }});\n'
        "-->\n"
    )


@click.command("quickstart")
@click.option(
    "--config",
    "config_path",
    type=click.Path(path_type=Path),
    default=Path("config.yaml"),
    show_default=True,
)
@click.option("--org", default="Local", show_default=True)
@click.option("--project", "project_name", default="Default", show_default=True)
@click.option("--environment", default="production", show_default=True)
@click.option("--api-host", default="127.0.0.1", show_default=True)
@click.option("--api-port", default=8788, show_default=True, type=int)
@click.option("--name", default="Browser SDK", show_default=True)
@click.option("--json", "as_json", is_flag=True, default=False)
@click.option(
    "--write-snippet",
    "snippet_out",
    type=click.Path(path_type=Path),
    default=None,
    help="Also write the script-tag snippet to this file.",
)
def quickstart_command(
    config_path: Path,
    org: str,
    project_name: str,
    environment: str,
    api_host: str,
    api_port: int,
    name: str,
    as_json: bool,
    snippet_out: Optional[Path],
) -> None:
    """Set up Retrace in one command and print a ready-to-paste script tag."""
    env_path = config_path.parent / ".env" if config_path.parent != Path("") else Path(".env")
    wrote_config, wrote_env = _write_stub_files_if_missing(config_path, env_path)

    cfg = load_config(config_path)
    cfg.run.data_dir.mkdir(parents=True, exist_ok=True)
    store = Storage(cfg.run.data_dir / "retrace.db")
    store.init_schema()

    workspace = store.ensure_workspace(
        org_name=org,
        project_name=project_name,
        environment_name=environment,
    )
    created = create_sdk_key(
        store,
        project_id=workspace.project_id,
        environment_id=workspace.environment_id,
        name=name,
    )

    ingest_url = f"http://{api_host}:{api_port}/api/sdk/replay"
    snippet = _emit_script_tag(api_key=created.key, ingest_url=ingest_url)

    if snippet_out is not None:
        snippet_out.parent.mkdir(parents=True, exist_ok=True)
        snippet_out.write_text(snippet)

    result = {
        "config_path": str(config_path),
        "env_path": str(env_path),
        "wrote_config": wrote_config,
        "wrote_env": wrote_env,
        "org_id": workspace.org_id,
        "project_id": workspace.project_id,
        "environment_id": workspace.environment_id,
        "sdk_key_id": created.id,
        "sdk_key": created.key,
        "ingest_url": ingest_url,
        "snippet": snippet,
    }
    if as_json:
        click.echo(json.dumps(result, indent=2))
        return

    click.echo("✓ Retrace is ready.\n")
    if wrote_config:
        click.echo(f"  wrote {config_path}")
    if wrote_env:
        click.echo(f"  wrote {env_path}")
    click.echo(f"  org/project/env: {org} / {project_name} / {environment}")
    click.echo(f"  SDK key:         {created.key}")
    click.echo(f"  ingest URL:      {ingest_url}")
    if snippet_out:
        click.echo(f"  snippet saved:   {snippet_out}")

    click.echo("\nPaste this into your app's <head> to start capturing replays:\n")
    click.echo("─" * 64)
    click.echo(snippet)
    click.echo("─" * 64)

    click.echo("\nNext steps:")
    click.echo(f"  1. retrace api serve --host {api_host} --port {api_port}")
    click.echo("  2. (in another terminal) retrace ui")
    click.echo("  3. interact with your app, then:")
    click.echo("     retrace api process-replays")
    click.echo("     retrace incident list")
    click.echo("")
    click.echo("To go end-to-end on the top incident in one command:")
    click.echo("  retrace incident auto --repo <org/name>")
